//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysbyteTest.EntityDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int AppointmentId { get; set; }
        public string FirstName { get; set; }
        public long Mobile { get; set; }
        public string Email { get; set; }
        public int Days_Id { get; set; }
        public int Time_Id { get; set; }
    
        public virtual tblDay tblDay { get; set; }
        public virtual tblTime tblTime { get; set; }
    }
}
